[package]
name = "cstormbird"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stormbird = { path = "../../stormbird"}

[build-dependencies]
cbindgen = "0.29"
